version: "3.8"

services:
  frontend:
    container_name: taspy-frontend
    build: ./dockerfiles/frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code

  backend:
    container_name: taspy-backend
    build: ./dockerfiles/backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    depends_on:
      - db
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    container_name: taspy-db
    image: postgres:12-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - $PWD/dockerfiles/db/init:/docker-entrypoint-initdb.d
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
